# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '68e3f430-99ba-4203-837c-92ebab3ae898'
  imageRepository-mysql: 'flask-blog-mysql'
  imageRepository-python: 'flask-blog-python'
  numberOfContainersToKeep: 10
  containerRegistry: 'registryupmpfg.azurecr.io'
  dockerfilePath-mysql: 'MySQL-DB/Dockerfile'
  dockerfilePath-python: 'part-2/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'registryupmpfg11388849-auth'
  k8sNamespace: 'python-blog'

  # Agent VM image name
  #poolName: 'Azure scale set UPM PFG'
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      #name: $(poolName)
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an MySQL image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository-mysql)
        dockerfile: $(dockerfilePath-mysql)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        cacheFrom: |
          $(containerRegistry)/$(imageRepository-mysql):latest
        pull: true

    - task: Docker@2
      displayName: Build and push an Flask image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository-python)
        dockerfile: $(dockerfilePath-python)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        cacheFrom: |
          $(containerRegistry)/$(imageRepository-mysql):latest
        pull: true

    - task: AzureCLI@2
      displayName: Clean up old images
      inputs:
        azureSubscription: 'Azure for Students(96f90eb2-51b8-45a7-8966-e361b1f51855)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Get list of Mysql images
          images=$(az acr repository manifest list-metadata --name $(containerRegistry) --repository $(imageRepository-mysql) --last $(numberOfContainersToKeep))

          # Loop through all images in repository
          for image in $(az acr repository show-tags --name $(containerRegistry) --repository $(imageRepository-mysql) --orderby time_desc)
          do
            # Check if image is not in the list of images to keep
            if [[ "$images" != *"$image"* ]]
            then
              # Delete image
              az acr repository delete --name $(containerRegistry) --image $(imageRepository-mysql):$image --yes
            fi
          done

          # Get list of Mysql images
          images=$(az acr repository manifest list-metadata --name $(containerRegistry) --repository $(imageRepository-python) --last $(numberOfContainersToKeep))
          
          # Loop through all images in repository
          for image in $(az acr repository show-tags --name $(containerRegistry) --repository $(imageRepository-python) --orderby time_desc)
          do
            # Check if image is not in the list of images to keep
            if [[ "$images" != *"$image"* ]]
            then
              # Delete image
              az acr repository delete --name $(containerRegistry) --image $(imageRepository-python):$image --yes
            fi
          done


    - publish: manifests
      artifact: manifests

    


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy 
    pool:
      #name: $(poolName)
      vmImage: $(vmImageName)
    environment: 'python-flask-blog-with-MySQL.python-blog'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - task: KubernetesManifest@0
            displayName: Deploy MySQL to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'AKS-UPM-PFG-Production-python-blog'
              namespace: '$(k8sNamespace)'
              manifests: |
                $(Pipeline.Workspace)/manifests/mysql-db-secret.yaml
                $(Pipeline.Workspace)/manifests/mysql-db-configmap.yaml
                $(Pipeline.Workspace)/manifests/mysql-db-persistance.yaml
                $(Pipeline.Workspace)/manifests/mysql-db-statefulset.yaml
                $(Pipeline.Workspace)/manifests/mysql-db-service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository-mysql):$(tag)
          
          - task: KubernetesManifest@0
            displayName: Deploy Flask to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'AKS-UPM-PFG-Production-python-blog'
              namespace: '$(k8sNamespace)'
              manifests: |
                $(Pipeline.Workspace)/manifests/flask-deployment.yaml
                $(Pipeline.Workspace)/manifests/flask-service.yaml
                $(Pipeline.Workspace)/manifests/flask-secret.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository-python):$(tag)


