# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '68e3f430-99ba-4203-837c-92ebab3ae898'
  imageRepository-mysql: 'flask-blog-mysql'
  imageRepository-python: 'flask-blog-python'
  containerRegistry: 'registryupmpfg.azurecr.io'
  dockerfilePath-mysql: 'MySQL-DB/Dockerfile'
  dockerfilePath-python: 'part-1/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'registryupmpfg11388849-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an MySQL image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository-mysql)
        dockerfile: $(dockerfilePath-mysql)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build and push an Flask image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository-python)
        dockerfile: $(dockerfilePath-python)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy 
    pool:
      vmImage: $(vmImageName)
    environment: 'gabrielenriquegonzalezlopezpythonflaskblogwithMySQL.python-blog'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'AKS-UPM-PFG-Production-python-blog'
              namespace: 'python-blog'
              command: 'apply'
              useConfigurationFile: true
              configuration: '/manifests/mysql-db-secret.yml'
          
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'AKS-UPM-PFG-Production-python-blog'
              namespace: 'python-blog'
              command: 'apply'
              useConfigurationFile: true
              configuration: '/manifests/mysql-db-persistance.yml'

          - task: KubernetesManifest@0
            displayName: Deploy MySQL to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/mysql-db-deployment.yml
                $(Pipeline.Workspace)/manifests/mysql-db-service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository-mysql):$(tag)
          
          - task: KubernetesManifest@0
            displayName: Deploy Flask to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/flask-deployment.yml
                $(Pipeline.Workspace)/manifests1/flask-service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository-python):$(tag)

