apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flaskapi
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: flaskapi
  type: ClusterIP