apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flask-blog-python
          image: registryupmpfg.azurecr.io/flask-blog-python
          #imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-blog-mysql-secrets
                key: db_root_password
          - name: MYSQL_DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: flask-blog-mysql-auth
          - name: MYSQL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: flask-blog-mysql-auth
          - name: 'MYSQL_DATABASE_DB'
            value: flask-blog
          - name: MYSQL_DATABASE_HOST
            value: flask-blog-mysql
          - name: MYSQL_DATABASE_PORT
            value: '3306'
          - name: FLASK_APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: flask_app_secret_key
                name: flask-blog-secret-key
          
