apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flaskapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: flaskapi
  type: ClusterIP