apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  serviceName: flask-blog-mysql
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: flask-blog-mysql
        image: registryupmpfg.azurecr.io/flask-blog-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-blog-mysql-secrets
              key: db_root_password
        - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: flask-blog-mysql-flask-auth
        - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: flask-blog-mysql-flask-auth
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: mysql-config
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-config
          configMap:
            name: mysql-config
