apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  init.sql: |-
    CREATE DATABASE flask_blog;
    
    USE flask_blog;

    CREATE TABLE tbl_user (
      user_id BIGINT NULL AUTO_INCREMENT,
      user_name VARCHAR(45) NULL,
      user_username VARCHAR(45) NULL,
      user_password VARCHAR(45) NULL,
      PRIMARY KEY (`user_id`)
    );

    INSERT INTO tbl_user (user_name, user_username, user_password) VALUES ('Alex', 'user_alex', '1234');
    INSERT INTO tbl_user (user_name, user_username, user_password) VALUES ('Manuel', 'user_alex', '5678');
    INSERT INTO tbl_user (user_name, user_username, user_password) VALUES ('Pedro', 'user_alex', '8910');

    CREATE TABLE posts (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        author_id INT NOT NULL,
        FOREIGN KEY (author_id) REFERENCES tbl_user(user_id)
    );

    INSERT INTO posts (title, content) VALUES ( 'Post de Comida', 'Comidas ricas');
    INSERT INTO posts (title, content) VALUES ( 'Post de Ropa', 'Ropa a la moda');
    INSERT INTO posts (title, content) VALUES ( 'Post de Coches', 'Coches lentos');
