apiVersion: v1
kind: Secret
metadata:
  name: flask-blog-mysql-secrets
type: Opaque
stringData:
  db_root_password: PfGpAs5

---
apiVersion: v1
kind: Secret
metadata:
  name: flask-blog-mysql-flask-auth
type: kubernetes.io/basic-auth
stringData:
  username: flask
  password: password
